#!/bin/sh
if [ -f /tmp/kravenskin ]; then
    mv -f /tmp/kravenskin /usr/share/enigma2/KravenVB/skin.xml
fi
if [ -d /tmp/graphics ]; then
    mv -f /tmp/graphics/*.* /usr/share/enigma2/KravenVB/graphics
fi
if [ -f /tmp/skin-user.xml ]; then
    mv -f /tmp/skin-user.xml /usr/lib/enigma2/python/Plugins/Extensions/KravenVB/data
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/KravenVB/plugin.py* ]; then
    wget -q -O /dev/null 'http://127.0.0.1/web/message?type=1&text=KravenVB%20wurde%20erfolgreich%20installiert.%0A%0AZur%20Nutzung%20rufen%20Sie%20das%20Plugin%20auf,%20speichern%20Ihre%20Einstellungen%0Aund%20starten%20die%20Oberfl%C3%A4che%20neu.&timeout=13' || true
fi
echo " .##....##.########.....###....##.....##.########.##....## "
echo " .##...##..##.....##...##.##...##.....##.##.......###...## "
echo " .##..##...##.....##..##...##..##.....##.##.......####..## "
echo " .#####....########..##.....##.##.....##.######...##.##.## "
echo " .##..##...##...##...#########..##...##..##.......##..#### "
echo " .##...##..##....##..##.....##...##.##...##.......##...### "
echo " .##....##.##.....##.##.....##....###....########.##....## "
echo " .........................................................."
echo "                    .##.....##..########..                 "
echo "                    .##.....##..##.....##.                 "
echo "                    .##.....##..##.....##.                 "
echo "                    .##.....##..########..                 "
echo "                    ..##...##...##.....##.                 "
echo "                    ...##.##....##.....##.                 "
echo "                    ....###.....########..                 "
echo "                                                           "
echo "              ...Skin successful installed.                "
