#!/bin/sh
if [ -f /tmp/skin.xml ]; then
    mv -f /tmp/skin.xml /usr/share/enigma2/KravenVB
fi
if [ -f /tmp/ibar.png ]; then
    mv -f /tmp/ibar.png /usr/share/enigma2/KravenVB
fi
if [ -f /tmp/ibaro.png ]; then
    mv -f /tmp/ibaro.png /usr/share/enigma2/KravenVB
fi
if [ -f /tmp/backg.png ]; then
    mv -f /tmp/backg.png /usr/share/enigma2/KravenVB
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/KravenVB/plugin.py ]; then
    wget -O /dev/null 'http://127.0.0.1/web/message?type=1&text=KravenVB%20wurde%20erfolgreich%20installiert.%0A%0AZur%20Nutzung%20rufen%20Sie%20das%20Plugin%20auf,%20speichern%20Ihre%20Einstellungen%20und%20starten%20die%20Oberfl%C3%A4che%20neu.&timeout=13'
fi
echo "                                                          "
echo "             ...Skin successful installed.                "
echo "                                                          "
