#!/bin/sh
echo "Checking for previous installations..."
if [ -f /usr/share/enigma2/KravenVB/ibar.png ]; then
    cp /usr/share/enigma2/KravenVB/ibar.png /tmp
fi
if [ -f /usr/share/enigma2/KravenVB/ibaro.png ]; then
    cp /usr/share/enigma2/KravenVB/ibaro.png /tmp
fi
if [ -f /usr/share/enigma2/KravenVB/backg.png ]; then
    cp /usr/share/enigma2/KravenVB/backg.png /tmp
fi
echo "                                                           "
echo "        The Skin KravenVB is now being installed...        "
echo "                                                           "
