#!/bin/sh
echo "Checking for previous installations..."
if [ -f /usr/share/enigma2/KravenVB/ibar.png ]; then
    cp /usr/share/enigma2/KravenVB/ibar.png /tmp
fi
if [ -f /usr/share/enigma2/KravenVB/ibaro.png ]; then
    cp /usr/share/enigma2/KravenVB/ibaro.png /tmp
fi
if [ -f /usr/share/enigma2/KravenVB/backg.png ]; then
    cp /usr/share/enigma2/KravenVB/backg.png /tmp
fi
if [ -f /usr/share/enigma2/KravenVB/skin.xml ]; then
    cp /usr/share/enigma2/KravenVB/skin.xml /tmp
    rm -rf /usr/share/enigma2/KravenVB
    rm -rf /usr/lib/enigma2/python/Components/Converter/KravenVB*
    rm -rf /usr/lib/enigma2/python/Components/Renderer/KravenVB*
		echo "                                                           "
		echo "             Previous KravenVB installation                "
		echo "                 was found and removed!                    "
		echo "                                                           "
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/KravenVB/plugin.py ]; then
    rm -rf /usr/lib/enigma2/python/Plugins/Extensions/KravenVB
		echo "                                                           "
		echo "              KravenVB configuration plugin                "
		echo "                 was found and removed!                    "
		echo "                                                           "
fi
echo "                                                           "
echo "        The Skin KravenVB is now being installed...        "
echo "                                                           "
