#!/bin/sh
echo "                                                           "
echo "        The Skin KravenVB is now being removed...           "
echo "                                                           "
